language: php
sudo: false
cache:
  directories:
  - vendor
install:
- composer install
script:
- ./vendor/bin/robo test
notifications:
  email:
    recipients:
      - astronati+fantasyfootballcalculator@vendini.com
    on_success: change
    on_failure: always
